<?php

namespace My\RecipesBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CaracteristicasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CaracteristicaRepository extends EntityRepository
{
}
