My\RecipesBundle\Entity\Recipe:
 type: entity
 table: recipes
 manyToOne:
  author:
    targetEntity: author
    joinColumn:
      name: author_id
      referencedColumnName: id
 id:
  id:
    type: integer
    generator: { strategy: AUTO }
 fields:
  name:
    type: string
    length: 255
  difficulty:
    type: string
    length: 40
  description:
    type: text