My\RecipesBundle\Entity\Usuario:
    type: entity
    table: null
    repositoryClass: My\RecipesBundle\Repository\UsuarioRepository
    oneToMany:
        elementos:
          targetEntity: Elemento
          mappedBy: categoria
    manyToMany:
        rolesObj:
            targetEntity: Rol
            joinTable:
                name: usuario_rol
                joinColumns:
                    usuario_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    rol_id:
                        referencedColumnName: id
            cascade: ["all"]
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nombre:
            type: string
            length: '40'
        apellido1:
            type: string
            length: '40'
        apellido2:
            type: string
            length: '40'
            nullable: true
        telefono:
            type: integer
            nullable: true
            unique: true
        mail:
            type: string
            length: '40'
            unique: true
        direccion:
            type: string
            length: 255
            nullable: true
        localidad:
            type: string
            length: '40'
            nullable: true
        codigoPostal:
            type: integer
            column: codigo_postal
            nullable: true
        ruta:
            type: string
            length: '255'
            unique: true
        nota:
            type: text
            nullable: true
        password:
            type: string
            length: '64'
        salt:
            type: string
            length: '64'
    lifecycleCallbacks: {  }
