my_recipes_homepage:
    path:     /
    defaults: { _controller: MyRecipesBundle:Default:index, name: "Pepe" }
my_recipes_contact:
    path:     /{_locale}/recipes/{recipe_id}
    defaults: { _controller: MyRecipesBundle:Recipe:showId, _locale: en }
    requirements:
        _locale: en|fr|de
##################################################################################
## Elemento
my_recipes_elementos_todos:
    pattern:  /elemento/{formato}/{categoria}
    defaults: { _controller: MyRecipesBundle:Elemento:showAll, formato: "bloques",categoria: "all"}
my_recipes_elemento_create:
    pattern:  /secured/elemento/create
    defaults: { _controller: MyRecipesBundle:Elemento:create }
my_recipes_elemento_ver_id:
    path: /elemento/{elemento_id}
    defaults: { _controller: MyRecipesBundle:Elemento:showId}
    requirements:
        elemento_id: \d+
my_recipes_elemento_ver_ruta:
    path: /elemento/{elemento_ruta}
    defaults: { _controller: MyRecipesBundle:Elemento:showRuta}
my_recipes_elemento_edit_id:
    pattern: /secured/elemento/{id}/edit
    defaults: { _controller: MyRecipesBundle:Elemento:edit}
    requirements:
        elemento_id: \d+
## Categoria
my_recipes_categoria_todas:
    pattern:  /categorias/{formato}
    defaults: { _controller: MyRecipesBundle:Categoria:showAll, formato: "bloques"}
my_recipes_categoria_create:
    pattern:  /secured/categoria/create
    defaults: { _controller: MyRecipesBundle:Categoria:create }
my_recipes_categoria_ver_id:
    path: /categoria/{categoria_id}
    defaults: { _controller: MyRecipesBundle:Categoria:showId}
    requirements:
        categoria_id: \d+
my_recipes_categoria_ver_ruta:
    path: /categoria/{categoria_ruta}
    defaults: { _controller: MyRecipesBundle:Categoria:showRuta}
my_recipes_categoria_edit_id:
    pattern: /secured/categoria/{id}/edit
    defaults: { _controller: MyRecipesBundle:Categoria:edit}
    requirements:
        categoria_id: \d+
## Caracteristica
my_recipes_caracteristica_create:
    pattern:  /caracteristica/create
    defaults: { _controller: MyRecipesBundle:Caracteristica:create }
my_recipes_caracteristica_ver_id:
    path: /caracteristica/{caracteristica_id}
    defaults: { _controller: MyRecipesBundle:Caracteristica:showId}
    requirements:
        caracteristica_id: \d+
my_recipes_caracteristica_ver_ruta:
    path: /caracteristica/{caracteristica_ruta}
    defaults: { _controller: MyRecipesBundle:Caracteristica:showRuta}
my_recipes_caracteristica_edit_id:
    pattern: /caracteristica/{id}/edit
    defaults: { _controller: MyRecipesBundle:Caracteristica:edit}
    requirements:
        caracteristica_id: \d+
## Usuario
my_recipes_usuario_create:
    pattern:  /secured/admin/usuario/create
    defaults: { _controller: MyRecipesBundle:Usuario:create }
my_recipes_usuario_register:
    pattern:  /usuario/register
    defaults: { _controller: MyRecipesBundle:Usuario:register }
my_recipes_usuario_ver_id:
    path: /secured/usuario/{usuario_id}
    defaults: { _controller: MyRecipesBundle:Usuario:showId}
    requirements:
        usuario_id: \d+
my_recipes_usuario_ver_id_registro:
    path: /usuario/{usuario_id}
    defaults: { _controller: MyRecipesBundle:Usuario:showId}
    requirements:
        usuario_id: \d+
my_recipes_usuario_ver_ruta:
    path: /secured/usuario/{usuario_ruta}
    defaults: { _controller: MyRecipesBundle:Usuario:showRuta}
my_recipes_usuario_edit_id:
    pattern: /secured/admin/usuario/{id}/edit
    defaults: { _controller: MyRecipesBundle:Usuario:edit}
    requirements:
        usuario_id: \d+


## Seguridad
my_recipes_homepage_secure:
    path:     /secured
    defaults: { _controller: MyRecipesBundle:Default:index }
login:
    path:   /login
    defaults:  { _controller: MyRecipesBundle:Security:login }
login_check:
    path:   /login_check
logout:
    path:   /logout
################# Ejemplos de los apuntes   ######################################
recipes_show_id:
    path:     /recipes/{recipe_id}
    defaults: { _controller: MyRecipesBundle:Recipe:showId }
    requirements:
        recipe_id: \d+

recipes_list:
    path:     /recipes/list/{page}
    defaults: { _controller: MyRecipesBundle:Recipe:list, page: 1 }
    requirements:
        page: \d+

recipes_show:
    path:     /recipes/{recipe_name}
    defaults: { _controller: MyRecipesBundle:Recipe:show }

recipes_create:
    path:     /create_recipe
    defaults: { _controller: MyRecipesBundle:Recipe:create }
    
recipes_topChefs:
    path: /top_Chefs
    defaults: { _controller: MyRecipesBundle:Recipe:topChefs }

my_recipes_author_create:
    pattern: /authors/create
    defaults: {_controller: MyRecipesBundle:Author:create }

my_recipes_author_show:
    path: /authors/{author_id}
    defaults: { _controller: MyRecipesBundle:Author:showId}
    requirements:
        recipe_id: \d+
my_recipes_recipe_edit:
    pattern:  /recipes/{id}/edit
    defaults: { _controller: MyRecipesBundle:Recipe:edit }
