my_recipes_homepage:
    path:     /{name}
    defaults: { _controller: MyRecipesBundle:Default:index, name: "Pepe" }
my_recipes_contact:
    path:     /{_locale}/recipes/{recipe_id}
    defaults: { _controller: MyRecipesBundle:Recipe:showId, _locale: en }
    requirements:
        _locale: en|fr|de
        
recipes_show_id:
    path:     /recipes/{recipe_id}
    defaults: { _controller: MyRecipesBundle:Recipe:showId }
    requirements:
        recipe_id: \d+

recipes_list:
    path:     /recipes/list/{page}
    defaults: { _controller: MyRecipesBundle:Recipe:list, page: 1 }
    requirements:
        page: \d+

recipes_show:
    path:     /recipes/{recipe_name}
    defaults: { _controller: MyRecipesBundle:Recipe:show }

recipes_create:
    path:     /create_recipe
    defaults: { _controller: MyRecipesBundle:Recipe:create }
    
recipes_topChefs:
    path: /top_Chefs
    defaults: { _controller: MyRecipesBundle:Recipe:topChefs }

my_recipes_author_create:
    pattern: /authors/create
    defaults: {_controller: MyRecipesBundle:Author:create }

my_recipes_author_show:
    path: /authors/{author_id}
    defaults: { _controller: MyRecipesBundle:Author:showId}
    requirements:
        recipe_id: \d+
my_recipes_recipe_edit:
    pattern:  /recipes/{id}/edit
    defaults: { _controller: MyRecipesBundle:Recipe:edit }

my_recipes_homepage_secure:
    path:     /secured
    defaults: { _controller: MyRecipesBundle:Default:index }
login:
    path:   /login
    defaults:  { _controller: MyRecipesBundle:Security:login }
login_check:
    path:   /login_check
logout:
    path:   /logout