services:
#    my_recipes.example:
#        class: My\RecipesBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
  my.twig.recipes_extension:
    class: My\RecipesBundle\Twig\RecipesExtension
    tags:
      - { name: twig.extension }
  my_recipes.form.type.difficulty:
    class: My\RecipesBundle\Form\Type\DifficultyType
    tags:
      - { name: form.type, alias: difficulty }
  my_recipes.form.type.author:
    class: My\RecipesBundle\Form\Type\AuthorType
    tags:
      - { name: form.type, alias: author }
  my_recipes.last_recipes:
    class: My\RecipesBundle\Model\LastRecipes
    arguments: ["@doctrine.orm.entity_manager"]
  my_recipes.recipe_creator:
    class: My\RecipesBundle\Model\RecipeCreator
    arguments: ["@doctrine.orm.entity_manager"]
  my_recipes.recipes_listener:
    class: My\RecipesBundle\Event\RecipesListener
    arguments: ["@mailer"]
    tags:
      - { name: kernel.event_listener, event: recipe.create, method: onRecipeCreate }
