My\RecipesBundle\Entity\Author:
 # getters:
 #   valid:
 #     - "True": { message: "No aceptamos recetas del autor" }
    properties:
      name:
        - NotBlank: ~
      surname:
        - NotBlank: ~
My\RecipesBundle\Entity\Categoria:
    getters:
      valid:
        - "True": { message: "No aceptamos fotos con ese nombre" }
    properties:
      nombre:
        - NotBlank: ~
      descripcion:
        - NotBlank: ~
My\RecipesBundle\Entity\Caracteristica:
  properties:
    nombre:
      - NotBlank: ~
    descripcion:
      - NotBlank: ~